services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
    ports:
      - '9090:9090'
    networks:
      - securescan-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - tempo
    ports:
      - '3001:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secretpassword
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    networks:
      - securescan-network

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres:5432/scans_db?sslmode=disable"
    command:
      - --collector.stat_statements
    ports:
      - "9187:9187"
    networks:
      - securescan-network

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    user: root
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
      - loki-wal:/wal
    networks:
      - securescan-network

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - securescan-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    depends_on:
      - redpanda
      - minio
    command: "-target=all -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    networks:
      - securescan-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=tempo
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9001:9001"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/tempo && minio server /data --console-address ':9001'
    networks:
      - securescan-network

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
    command: >
      redpanda start --overprovisioned
      --mode=dev-container
      --kafka-addr=PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    networks:
      - securescan-network

volumes:
  loki-data:
  loki-wal:

networks:
  securescan-network:
    driver: bridge
