{
 "title": "SecureScan",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan Orchestrator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"scan-orchestrator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Requests & Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    {__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Successful Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\",code=~\"2..\"}[$__range]))\n/\n  sum(increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Failed Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\",code=~\"4..|5..\"}[$__range]))\n/\n  sum(increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[$__range]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Requests by Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (url) (\n  increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Status Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "round(\n  sum by(code)(\n    increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (url,method) (\n  rate({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (url,method) (\n  increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of requests by http status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (code) (\n  rate({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (code) (\n  increase({__name__=~\"api_gateway_requests_total|scan_orchestrator_requests_total\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/scan-orchestrator\"} != \"/metrics\" | json"
    }
   ]
  }
 ]
}